baseURL = 'https://rlnorthcutt.github.io/hugo-sample/'
languageCode = 'en-us'
title = 'Hugo Sample Site'
theme = 'hugo-classless'

[params]
  author = "Hugo Sample"
  description = "A sample static site for open source projects using Hugo"
  theme = "css/classless.css"
  
themes = {
  { name = "HTML only", url = "" },
  { name = "Skeleton.css", url = "https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css"},
  { name = "Cosmo.css", url = "https://cdn.jsdelivr.net/gh/cspablocortez/cosmocss@latest/cosmo.min.css" },
  { name = "Pico", url = "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css" },
  { name = "Pico-Fluid", url = "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.fluid.classless.min.css" },
  { name = "Water.css", url = "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css" },
  { name = "Simple.css", url = "https://cdn.simplecss.org/simple.min.css" },
  { name = "New.css", url = "https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" },
  { name = "PerfectMFWS", url = "https://perfectmotherfuckingwebsite.com/fuckingstyle.css" }
]
  
  faviconSVG = "/favicon.svg"
  faviconICO = "/favicon.ico"
  appleTouchIcon = "/apple-touch-icon.png"

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "Pages"
  pageRef = "/pages"
  weight = 20

[[menu.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 30

[[menu.main]]
  name = "News"
  pageRef = "/news"
  weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    style = "nord"
